apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-01
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-disk-master
  local:
    path: /mnt/hgfs/Elastic_task/esdata/master
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - localhost.localdomain      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-02
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-disk-data
  local:
    path: /mnt/hgfs/Elastic_task/esdata/data1
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - localhost.localdomain  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-03
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-disk-data
  local:
    path: /mnt/hgfs/Elastic_task/esdata/data2
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - localhost.localdomain  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-04
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-disk-data
  local:
    path: /mnt/hgfs/Elastic_task/esdata/data3
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - localhost.localdomain  
